# Generated by Django 2.1.7 on 2019-03-05 20:06

from django.db import migrations, models
import issues.models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_time_posted',
            field=models.DateTimeField(default=issues.models.Issue.date_time_posted_default),
        ),
        migrations.AddField(
            model_name='issue',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(default='default', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='issueType',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=10, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=10, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
