# Generated by Django 2.1.7 on 2019-03-05 20:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20190305_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
