# Generated by Django 2.1.7 on 2019-03-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20190319_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='poster',
        ),
    ]
