# Generated by Django 2.1.7 on 2019-03-31 23:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_remove_issue_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='posterEmail',
            field=models.EmailField(default='testuser@kiuc.coop', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='posterName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='posterPhone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
