# Generated by Django 2.2 on 2019-04-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20190408_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='image',
        ),
    ]
