# Generated by Django 2.2 on 2019-04-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_remove_issue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(default='default', upload_to='issueImage'),
            preserve_default=False,
        ),
    ]
