# Generated by Django 2.2 on 2019-06-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_issue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
