# Generated by Django 2.2 on 2019-06-08 21:07

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_issue_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='issueImage'),
        ),
    ]
