# Generated by Django 2.2 on 2019-06-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_auto_20190608_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(upload_to='issueImage'),
        ),
    ]
