# Generated by Django 2.2 on 2019-06-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_auto_20190608_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='issueImage'),
            preserve_default=False,
        ),
    ]
