# Generated by Django 2.2 on 2019-06-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_issue_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='issueImage'),
        ),
    ]
