# Generated by Django 2.1.7 on 2019-03-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20190327_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
