# Generated by Django 2.2 on 2019-05-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20190511_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='newIssueNotifications',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
